name: Continuous Integration

on:
  push:
    branches:
      - UI/UX
      - google
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 16.16.0

      - run: npm ci 
      - run: npm test
      - run: npm run build
      - run: npm run deploy

    