name: iOS

on: [push, pull_request]

jobs:
    check:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 
          uses: actions/setup-node@v1
          with:
            node-version: 16.16.0
        

        - run: npm ci--legacy-peer-deps